a. SELECT COUNT(*), GUEST.GuestID, GUEST.GuestName FROM GUEST INNER JOIN RESERVATION ON GUEST.GuestID = RESERVATION.GuestID GROUP BY GUEST.GuestID, GUEST.GuestName HAVING COUNT(*) > 2



b.

SELECT GUEST.GuestName, GUEST.ContactNumber FROM GUEST INNER JOIN RESERVATION ON GUEST.GuestID = RESERVATION.GuestID WHERE RESERVATION.CheckInDate AND RESERVATION.CheckOutDate BETWEEN 2018-12-31 AND 2020-1-1



c.

SELECT GUEST.GuestName, GUEST.ContactNumber, RESERVATION.CheckInDate, RESERVATION.CheckOutDate FROM GUEST INNER JOIN RESERVATION ON GUEST.GuestID = RESERVATION.GuestID INNER JOIN ROOM ON Room.RoomID = RESERVATION.RoomID WHERE Room.Name = 'Deluxe Suite'



d. 

CREATE TABLE RESERVATION(

ReservationID nvarchar(20) PRIMARY KEY,

RoomID nvarchar(20) FEREIGN KEY REFERENCES Room(RoomID),

GuestID nvarchar(20) FEREIGN KEY REFERENCES Guest(GuestID),

CheckInDate date,

CheckOutDate date,



e. 

Peak Season : UPDATE ROOMDETAIL SET Price = (Price + 20/100)) 

After Peak Season: UPDATE ROOMDETAIL SET Price = (Price - 10/100))